# 本行为yaml文件注释范例
# yaml配置格式以空格缩进区分层级关系
# key后面紧跟一个冒号 冒号后需加一个空格方可填写value

windows_tool:
  
  # 本工具模板地址
  tool_open_url: "本工具开源地址：https://github.com/ClimbSnail/esp_win_tool"

  # 工具的名称
  tool_name: "QF_HEYE 专用下载工具 "
  
  # 自定义QQ群信息 一共需填写两个群号，中间英文的分号隔开
  qq_info: QQ_1群 216066270,QQ_2群 暂无

  # 是否生效激活组控件
  activate: true

  # 屏蔽清空式烧录选项
  empty_burn_enable: false
  
  # 自定义额外的视频或文档链接
  info_url_0: <html><head/><body><p>视频演示：OSHWHub开源页</p></body></html>
  info_url_1: <html><head/><body><p>用户手册：https://kdocs.cn/l/cabR1eYE2KIK</p></body></html>
  
  # main_app_rules为页面搜索框中搜索主程序的适配规则
  # 下面的匹配规则为 搜索包含 _app.bin 字段
  main_app_rules: _app.bin
  # 主用户程序的刷写地址
  main_app_addr: "0x10000"
  # 辅助bin文件的
  firmware_info_list:
    # 这里可添加n个bin文件信息（以一行"-"符号隔离），会将指定格式以指定地址刷入
    -
      filepath: ./base_data/QF-HEYE_Firmware_V1.0.2_bootloader.bin
      addr: "0x0"
    - 
      filepath: ./base_data/QF-HEYE_Firmware_V1.0.2_partition-table.bin
      addr: "0x8000"
      
  # 预留的读取激活码的本地缓存文件 用于不在联网状态下使用（本字段需要配合固件联调）
  temp_sn_recode_path: temporary_sn_recode.txt
  # 激活码查询的api 需要激活码管理员有服务器
  search_sn_url: 
  # 获取最新固件版本的api
  get_firmware_new_ver_url: 
  # 自动激活的api 用于工厂批量生产（应设超级权限）
  activate_sn_url: 
